### ISSUE TITLE
[Docs] 一个介绍开发流程的README

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/gi-assets-xlab#1]
首先自己跑通一遍，然后编写README。

草稿：

- [ ] 需要用`nvm`来管理Node版本
- [ ] 在实现中，asset、component、CONFIG、registerMeta的关系（参考[语雀文档](https://www.yuque.com/antv/gi/bw1fhv#z7hCn)）
- [ ] 解释为什么山果说“整个pages里的代码都可以后续在gi官方站点上导出配置覆盖，只有 update.ts文件，是一个update函数，根据你导出的默认配置和资产，进行本地自定义资产的研发”
- [ ] 如果资产里有新component，编辑update.ts即可。
- [ ] 一个component导出时需要提供`{info, component, registerMeta}`
- [ ] 端口是8000
- [ ] 大路径：用脚手架开发自定义资产、将开发好的自定义资产导入G6VP平台、用平台拖拉拽的方式开发一个画布（官方资产和自定义资产都会用到）、导出画布为SDK后静态部署
- [ ] 在G6VP拖拉拽的时候其实相当于在改CONFIG，用导出的SDK替换cli的pages相应内容，是没有地方拖拉拽的，这就要求用代码的方式给自定义的资产中的组件传入参数，控制其变化。

**Comment by tyn1998** [comment]
已经要写[文档](https://ant-xlab.yuque.com/org-wiki-ant-xlab-fsufaz/vkcfxl/bsnh8sk7esgefw6o)的“如何开发资产”这一部分了，还是需要确认几个问题，弄清楚这几个问题，我应该会有更好的理解。麻烦@pomelo-nwu有空的时候能够解答一下~

1. 官方人员是怎么开发官方资产的？需要脚手架吗？（我想应该是直接在G6VP仓库中开发的吧）
2. 自定义资产为什么不能直接在G6VP仓库上开发呢？为什么要起脚手架。（那肯定是这样子呀，我之所以这么问，是因为目前的脚手架npm run start跑出来的直接是一个图App，而不是一个G6VP平台。这样的话，我怎么测试资产在“编辑画布”时的功能是否正常呢，比如怎么在页面上测试registerMeta的各个配置项是否正常工作呢？）
3. 直接在G6VP连接好数据源（比如说neo4j）然后导出为SDK并覆盖脚手架的pages的几个文件，那脚手架中的services/目录还有用吗？换句话说，我们的资产要写service吗？
4. 山果加的XlabLayout这个component有什么用？我的理解是一共只要开发两个component，一个是“节点属性面板”，另一个是“搜索框”。
5. 有没有其他非官方人员开发自定义资产的案例？他们一般是：1、先用G6VP官方资产搭好绝大多数功能然后导出SDK覆盖脚手架中的pages进行剩下的自定义资产开发；还是2、先用G6VP搭一个最基本的画布然后导出SDK覆盖脚手架中的pages进行自定义资产开发；还是3、不需要G6VP导出SDK，直接用脚手架的pages进行自定义资产开发，开发完导入到G6VP再和官方资产一起搭建画布。山果推荐我们采用哪种方式？

**Comment by pomelo-nwu** [comment]
A1：G6VP成员主要开发两类资产，一类是开源的资产，都是通用的，因此是直接在 G6VP 仓库中开发。一类是「内网业务域资产」这类资产都是通过脚手架安装开发的，仓库也都是在内网的代码托管平台中，消费的时候，通过内网登陆接口判断用户权限，进行「业务域」资产的下发CDN资源。

A2:「自定义资产为什么不能直接在G6VP仓库上开发」根据经验，很多自定义资产都是具有业务域特色的资产，这部分资产，用户不一定愿意开源。即使有开源意愿，比如 `gi-assets-xlab` 也会因为该资产不够通用，而不能放到G6VP的官方资产库中，只能作为自己的业务领域的开源资产。「怎么在页面上测试registerMeta的各个配置项是否正常工作呢」这个就需要本地 `npm run build:umd:watch && npm run serve`  然后手动上传到 G6VP 的官方站点上进行测试。因为开发的90%工作量都在资产本身的开发，因此我们才采用这样的方式，用户本地 npm run dev 先用一个app模拟资产的研发，这样有热更新，开发体验更好。等开发差不多了，用umd包的方式，放入到g6vp站点做全流程测试。未来我们希望也加入一个 gi-assets-testing 更好来解决这个问题

A3: 如果直接使用现有的数据源，则本地的services目录是无用的，之所以有这个目录，是因为脚手架要提供「自定义数据源」的demo效果。如果用户没有自定义数据源的需求，可以删掉。

A4: XlabLayout 是一个容器布局资产，和其他两个components相比，它是来控制整个 app 应用的整体页面布局的，和「services」一样，都是为了演示功能用的， 如果你们不需要「自定义页面布局」，这个资产也是可以删掉的。

A5: 三种方式都可以。官方推荐的是方案一，因为我们希望用户自定义的资产都能够在G6VP平台上消费，所以理论上，pages里的app案例，应该是直接在g6vp平台上导出的

**Comment by tyn1998** [comment]
非常感谢 @pomelo-nwu 的细致回答，解决了我所有困惑！对于Q5，由于我们还没有设计出最终的图应用形态，所以可能是先用方案二开发一段日子，然后再用方案一替换一下pages继续开发。

也请 @wj23027 同学多多体验 G6VP 平台并设想一下 G6VP + X-lab 会导出一个怎么样的图应用 :)

**Comment by wj23027** [comment]
好的~我已经着手体验 G6VP 平台并思考与 X-lab 结合的图应用的可能性，目前还处于探索和研究阶段

**Comment by tyn1998** [comment]
哈啰 @wj23027，设计进展如何？有可以预览的设计方案链接吗？

**Comment by wj23027** [comment]
我这两天思考了一下不同用户的需求以及相关的用户故事，基本如下，理解可能还比较浅薄，欢迎指正~

#### 开源爱好者
- 需求：希望从整体上了解多个仓库和贡献者之间的关系，以便进行数据分析和洞察，进一步参与和贡献。
- 功能需求：能够展示仓库和贡献者之间的合作关系，提供可视化的网络图以及相关统计数据，如连接的强度、共同参与的项目等。
1. 浏览主页，查看热门的仓库和贡献者。
2. 选择一个感兴趣的仓库或贡献者，进入其详细页面。
3. 在仓库或贡献者页面上查看其在网络图中的位置和关联关系。
4. 点击网络图上的节点，查看节点的详细信息和统计数据。
5. 可以自由展开或隐藏网络图的节点，以适应自己的关注重点。
6. 可以使用搜索或筛选功能，聚焦于特定仓库或贡献者。
7. 选择多个仓库，观察多个仓库的聚合数据，了解某个社区的节点直接的关联关系以及统计数据。

#### 项目管理者
 - 需求：希望追踪特定仓库的贡献者活动，了解项目的进展和参与度。
 - 功能需求：能够展示特定仓库的贡献者信息和活动历史，以及相关的统计指标，如提交频率、活跃度评分等。
 1. 搜索或选择特定的仓库，进入仓库的页面。
 2. 查看仓库的详细信息和统计数据和贡献者关系。
 3. 点击贡献者节点，查看其在网络图中的关联关系及其统计数据，评估其参与度和贡献程度。
 4. 可以使用筛选功能、展开或隐藏网络图的节点，以关注特定的贡献者或关系。
 5. 选中多个仓库，关注多个仓库的聚合数据。
    
#### 开发者
- 需求：希望在一个综合视图中了解自己参与的多个仓库和其他贡献者的活动。
- 功能需求：能够展示开发者参与的多个仓库，显示个人和其他贡献者的活动，便于了解自己在不同项目中的贡献和合作情况。
 1. 查看自己参与的多个仓库和其他贡献者的活动。
 2. 点击自己在网络图中的节点，查看自己的详细信息和统计数据。
 3. 点击其他贡献者节点，查看其在网络图中的位置和关联关系。
 4. 可以使用搜索或筛选功能、选择某些特定的节点，以关注特定的贡献者或关系。
 5. 根据网络图和活动历史了解自己在不同项目中的贡献和合作情况，可以从网络图中获取灵感和合作机会。
    
#### 人才猎手
  - 需求：希望能够了解特定开发者在开源项目中的参与情况和贡献程度，以评估其技术能力和参与度。
  - 功能需求：能够搜索和查看特定开发者的贡献记录、参与的仓库，以及相关的统计数据，为招聘决策提供参考。
 1. 搜索和查看特定开发者的贡献记录和参与的仓库。
 2. 点击开发者节点，查看其在网络图中的位置和关联关系。
 3. 查看开发者的详细信息和统计数据，如openrank、活跃度评分等。
 4. 根据开发者在开源项目中的参与情况和贡献程度进行评估。
 5. 可以从网络图中观察与开发者关联节点的openrank权重以及关联程度，对其技术能力和参与度有整体了解。

**Comment by andyhuang18** [comment]
我额外想了一部分的用户角色故事，作为补充。

**新手贡献者** 
- 需求：作为一个新手贡献者，希望能够找到适合技能水平和兴趣的开源项目，并与其他贡献者进行交流和学习。 

功能需求：

1. 在主页上展示热门的仓库和贡献者，以便新手快速了解当前流行和活跃的项目。
2. 提供筛选功能，根据编程语言、难度级别或项目类型等条件，找到适合自己的项目。
3. 查看仓库或贡献者的详细页面，了解他们的技能、项目经验和贡献历史。
4. 在仓库页面上可以查看该项目的贡献指南、待办事项和提问区域，方便新手入门和提问。
5. 可以通过网络图了解仓库和贡献者之间的关联关系，找到可以与之合作或学习的贡献者。
6. 提供在线交流平台或论坛，让新手可以与其他贡献者交流经验、寻求帮助和共同解决问题。

**数据分析师** 
- 需求：作为一名数据分析师，需要从开源社区中获取数据，分析社区的活跃度、贡献模式和发展趋势，为决策者提供洞察和建议。 

功能需求：

1. 提供社区的整体统计数据，如活跃用户数量、贡献量、项目增长率等，以便分析社区的整体健康状况。
2. 可以根据时间范围和关键词筛选数据，进行特定领域或项目的深入分析。
3. 在网络图中展示仓库和贡献者之间的合作关系，以便观察社区中的核心成员、贡献网络和合作模式。
4. 可以将网络图导出为可视化报告或图表，以便向决策者和团队分享分析结果。
5. 提供数据导出功能，以便将数据用于自定义的数据分析工具和模型。
6. 可以与其他数据分析师和研究人员交流，分享分析方法和发现，促进开源社区数据的研究和探索。

**导师/指导者** 
- 需求：作为一位开源社区的导师或指导者，我希望能够跟踪和指导新手贡献者的成长，并为他们提供帮助和反馈。

功能需求：

1. 可以查看新手贡献者的学习进度和贡献历史，以便评估他们的成长和需求。
2. 在贡献者的详细页面上提供反馈和建议，帮助他们改进和学习。
3. 可以与新手贡献者进行一对一的在线交流，回答问题、解决疑惑和提供指导。
4. 提供导师和学员之间的互动平台，促进经验分享和学习交流。
5. 可以设定目标和任务，帮助新手贡献者更好地规划和管理他们的学习和贡献计划。

**跨项目贡献者** 
- 需求：作为一个开源社区的跨项目贡献者，希望能够了解不同项目之间的关联性，以便找到可以在多个项目中贡献的机会。 

功能需求：

1. 可以查看不同项目之间的关联关系和合作模式，了解项目间的交叉贡献机会。
2. 提供搜索和筛选功能，以便找到在多个项目中活跃的贡献者和相关主题。
3. 可以查看贡献者在多个项目中的贡献历史和影响力，以便评估其跨项目的专业能力和可靠性。
4. 提供跨项目的贡献统计和奖励体系，激励和表彰跨项目贡献者的贡献和成就。

**潜在合作伙伴/赞助商** 
- 需求：作为一个潜在的合作伙伴或赞助商，希望能够了解开源社区的规模、影响力和质量，以便评估合作或赞助的机会。 

功能需求：

1. 提供开源社区的整体统计数据和指标，如贡献者数量、项目数量和用户活跃度等。
2. 可以查看社区的用户群体和受众分布，了解其定位和影响力范围。
3. 提供成功案例和项目介绍，展示开源社区的成果和影响。
4. 可以查看社区的质量控制和社区准则，以确保与合作伙伴的价值观和利益保持一致。
5. 提供联系方式和合作流程，便于潜在合作伙伴和赞助商与开源社区进行沟通和合作洽谈。

**Comment by pomelo-nwu** [comment]
如果我们正常写业务逻辑，代码大概是这样的
![image](https://github.com/X-lab2017/gi-assets-xlab/assets/10703060/65d0bc16-20ec-49ef-a9d6-4883a4ca1608)
对应的页面是这样的：
![image](https://github.com/X-lab2017/gi-assets-xlab/assets/10703060/b8f7100f-e8c4-4014-965b-c401cbec97ab)
